export interface BaseErrorProps {
  message: string;
  code: ApiErrorCode;
  error?: string | object;
  context?: object;
}

export enum ApiErrorCode {
  /** AUTH ERRORS CODES */
  AUTHENTICATION_ERROR = 1000,
  AUTHENTICATION_INVALID_TOKEN = 1001,
  AUTHENTICATION_TFA_FAILED = 1002,
  AUTHENTICATION_LOGIN_ATTEMPT_EXCEEDED = 1003,
  AUTHENTICATION_USER_ALREADY_REGISTERED = 1004,
  AUTHENTICATION_GOOGLE_NOT_ESTABLISHED = 1005,

  /** VALIDATION ERRORS CODES */
  VALIDATION_ERROR = 2000,
  VALIDATION_TFA_CONFIG = 2001,
  VALIDATION_FILE_INVALID = 2002,
  VALIDATION_FILE_TOO_LARGE = 2003,
  VALIDATION_FILE_NOT_FOUND = 2004,
  VALIDATION_INVALID_PASSWORD = 2005,
  VALIDATION_ANALYZER_NOT_FOUND = 2006,
  VALIDATION_REPLY_GENERATOR_NOT_FOUND = 2007,

  /** ACCESS-CONTROL ERRORS CODES  */
  ACCESS_CONTROL_ERROR = 3000,
  ACCESS_CONTROL_ROOT_DELETION = 3001,

  /** DATABASE ERRORS CODES */
  DATABASE_ERROR = 4000,
  DATABASE_VALIDATION = 4001,
  DATABASE_DUPLICATE = 4002,
  DATABASE_FOREIGN_KEY = 4003,
  DATABASE_NOT_FOUND = 4004,
  DATABASE_NULL_VALUE = 4005,
  DATABASE_DYNAMO_NOT_FOUND = 4006,

  /** API ERRORS CODES  */
  API_ERROR = 5000,
  API_FILE_UPLOAD = 5001,
  API_FILE_DOWNLOAD = 5002,
  API_FILE_DELETION = 5003,
  API_CONTEXT_ERROR = 5004,
  API_MAILING_ERROR = 5005,
  API_POSTMARK_API_ERROR = 5009,
}
