export enum MikroOrmOperatorToGraphQLFilterField {
  $in = 'IN',
  $nin = 'NIN',
  $eq = 'EQ',
  $ne = 'NE',
  $gt = 'GT',
  $lt = 'LT',
  $gte = 'GTE',
  $lte = 'LTE',
  $like = 'LIKE',
  $ilike = 'ILIKE',
  $contains = 'CONTAINS',
  $contained = 'CONTAINED',
  $overlap = 'OVERLAP',
  $size = 'SIZE',
  $or = 'OR',
  $and = 'AND',
}
